package com.censkh.game.generation;

public enum ChunkType {
	LEFT_TO_RIGHT, TOP_TO_BOTTOM, ENTRANCE_ALL, ENTRANCE_LEFT, ENTRANCE_RIGHT, OBSTACLE, ENTRANCE_RIGHT_DOWN, WALL_DOWN, WALL_TOP, ENTRANCE_UP_LEFT, ENTRANCE_DOWN, ENTRANCE_UP
}
