package com.censkh.game.tile;

public enum TileRenderType {
	AIR_UP_LEFT(5),
	AIR_LEFT_RIGHT(2),
	AIR_UP_RIGHT(6),
	AIR_UP_DOWN(3),
	AIR_DOWN_RIGHT(11),
	AIR_DOWN_LEFT(10),
	AIR_NONE(1),
	AIR_ALL(0),
	AIR_UP(14),
	AIR_DOWN(19),
	AIR_LEFT(9),
	AIR_RIGHT(24),
	AIR_UP_LEFT_RIGHT(8),
	AIR_UP_LEFT_DOWN(12),
	AIR_UP_RIGHT_DOWN(13),
	AIR_DOWN_LEFT_RIGHT(7),
	AIR_CORNERS_ALL(4),
	AIR_LEFT_UP_CORNER_BRIGHT(15),
	AIR_UP_RIGHT_CORNER_BLEFT(16),
	AIR_DOWN_RIGHT_CORNER_TLEFT(21),
	AIR_DOWN_LEFT_CORNER_TRIGHT(20),
	AIR_DOWN_CORNER_TLEFT_TRIGHT(23),
	AIR_UP_CORNER_BRIGHT_BLEFT(22),
	AIR_LEFT_CORNER_TRIGHT_BRIGHT(17),
	AIR_RIGHT_CORNER_TLEFT_BLEFT(18),
	AIR_DOWN_CORNER_TLEFT(26),
	AIR_DOWN_CORNER_TRIGHT(25),
	AIR_UP_CORNER_BLEFT(27),
	AIR_UP_CORNER_BRIGHT(28),
	AIR_LEFT_CORNER_TRIGHT(29),
	AIR_LEFT_CORNER_BRIGHT(34),
	AIR_RIGHT_CORNER_BLEFT(32),
	AIR_RIGHT_CORNER_TLEFT(33),
	AIR_NONE_CORNER_TLEFT(37),
	AIR_NONE_CORNER_TRIGHT(38),
	AIR_NONE_CORNER_BLEFT(39),
	AIR_NONE_CORNER_BRIGHT(40),
	AIR_NONE_CORNER_TLEFT_BRIGHT_TRIGHT(30),
	AIR_NONE_CORNER_TLEFT_BRIGHT_BLEFT(36),
	AIR_NONE_CORNER_TLEFT_BLEFT_TRIGHT(31),
	AIR_NONE_CORNER_BRIGHT_TRIGHT_BLEFT(35),
	AIR_NONE_CORNER_TRIGHT_BLEFT(41),
	AIR_NONE_CORNER_TLEFT_BRIGHT(42),
	AIR_NONE_CORNER_TLEFT_TRIGHT(43),
	AIR_NONE_CORNER_BLEFT_BRIGHT(44),
	AIR_NONE_CORNER_TRIGHT_BRIGHT(45),
	AIR_NONE_CORNER_BLEFT_TLEFT(46);
	private final int id;
	
	private TileRenderType(int id) {
		this.id = id;
	}
	
	public int getId() {
		return id;
	}
	
}
